// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution01.ClimbStairs(System.Int32)~System.Int32")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution02.Fib(System.Int32)~System.Int32")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution03.Tribonacci(System.Int32)~System.Int32")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution04.MinCostClimbingStairs(System.Int32[])~System.Int32")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution05.Rob(System.Int32[])~System.Int32")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution06.DeleteAndEarn(System.Int32[])~System.Int32")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution07.UniquePaths(System.Int32,System.Int32)~System.Int32")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution08.MinPathSum(System.Int32[][])~System.Int32")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution09.UniquePathsWithObstacles(System.Int32[][])~System.Int32")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution10.MinimumTotal(System.Collections.Generic.IList{System.Collections.Generic.IList{System.Int32}})~System.Int32")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution11.MinFallingPathSum(System.Int32[][])~System.Int32")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution12.MaximalSquare(System.Char[][])~System.Int32")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution13.LongestPalindrome(System.String)~System.String")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution14.WordBreak(System.String,System.Collections.Generic.IList{System.String})~System.Boolean")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution15.LongestPalindromeSubseq(System.String)~System.Int32")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution16.MinDistance(System.String,System.String)~System.Int32")]
