// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution01.ClimbStairs(System.Int32)~System.Int32")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution02.Fib(System.Int32)~System.Int32")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution03.Tribonacci(System.Int32)~System.Int32")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution04.MinCostClimbingStairs(System.Int32[])~System.Int32")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution05.Rob(System.Int32[])~System.Int32")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution06.DeleteAndEarn(System.Int32[])~System.Int32")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution07.UniquePaths(System.Int32,System.Int32)~System.Int32")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution08.MinPathSum(System.Int32[][])~System.Int32")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution09.UniquePathsWithObstacles(System.Int32[][])~System.Int32")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution10.MinimumTotal(System.Collections.Generic.IList{System.Collections.Generic.IList{System.Int32}})~System.Int32")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution11.MinFallingPathSum(System.Int32[][])~System.Int32")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution12.MaximalSquare(System.Char[][])~System.Int32")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution13.LongestPalindrome(System.String)~System.String")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution14.WordBreak(System.String,System.Collections.Generic.IList{System.String})~System.Boolean")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution15.LongestPalindromeSubseq(System.String)~System.Int32")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution16.MinDistance(System.String,System.String)~System.Int32")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution17.MinimumDeleteSum(System.String,System.String)~System.Int32")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution18.NumDistinct(System.String,System.String)~System.Int32")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution19.LengthOfLIS(System.Int32[])~System.Int32")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution20.FindNumberOfLIS(System.Int32[])~System.Int32")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution21.FindLongestChain(System.Int32[][])~System.Int32")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution22.LongestSubsequence(System.Int32[],System.Int32)~System.Int32")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution23.LongestArithSeqLength(System.Int32[])~System.Int32")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution24.MaxEnvelopes(System.Int32[][])~System.Int32")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution25.LongestObstacleCourseAtEachPosition(System.Int32[])~System.Int32[]")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution26.LongestCommonSubsequence(System.String,System.String)~System.Int32")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution27.MaxUncrossedLines(System.Int32[],System.Int32[])~System.Int32")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution28.MinInsertions(System.String)~System.Int32")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution29.MaxProfit(System.Int32[])~System.Int32")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution30.MaxProfit(System.Int32[],System.Int32)~System.Int32")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution31.MaxProfit(System.Int32[])~System.Int32")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "<Pending>", Scope = "member", Target = "~M:DynamicProgramming.Solution32.MaxProfit(System.Int32,System.Int32[])~System.Int32")]
